### ISSUE TITLE
jade undefined 

### ISSUE THREAD

**Issue by mividtim** [brunch/jade-brunch#27]
Hello.

I'm trying to use Jade and Chaplin with Brunch.  I cannot seem to get a simple Jade template working, since jade is not globally defined:

Uncaught ReferenceError: jade is not defined

Here is the offending line of code in my templates.js:

buf.push("<a href=\"i.href\" class=\"header-link\">" + (jade.escape(null == (jade_interp = i.title) ? "" : jade_interp)) + "</a>");

The issue is right at the "jade.escape," since as I said, jade is not globally defined, and is not require'd anywhere in the file.  I thought it may be an issue with separating templates to a separate file, but joining to app.js did not resolve the issue - it doesn't require or define jade anywhere either.

Another route I tried to go down is to add jade to the window object in my initialization script:

window.jade = require "jade"

Then, the jade object IS globally defined, but I get issues with __filename not being defined.  I assume this is because the jade version I have is assuming a Browserify environment, whereas Brunch does its own CommonJS wrapping, and doesn't define low-level Node globals like Browserify does.

I then went down a long rabbit-hole of trying to use browserify-brunch, but a) I can't seem to get it to work, and documentation and comments are REAL thin, and b) some comments I have seen indicate that this completely negates the main reason to use Brunch (speed), since Browserify basically takes over the entire build process, not just the CommonJS wrapping - so all files are built on any file update.

Here is the complete Jade template that is having the issue - as I said, it's rather benign:

each i in items
  a(class="header-link", href="i.href")=i.title

Here are the versions of all of my dependencies:

  "dependencies": {
    "chaplin": "^1.1.1",
    "jquery": "^2.2.0"
  },
  "devDependencies": {
    "auto-reload-brunch": "^1.8.1",
    "clean-css-brunch": "^1.8.0",
    "coffee-script-brunch": "^1.8.3",
    "jade-brunch": "^1.8.2",
    "static-jade-brunch": "^1.8.0",
    "stylus-brunch": "^1.8.1",
    "uglify-js-brunch": "^1.7.8"
  }

One las thought on my part - should I skip using static-jade-brunch?  Could that be causing the issue?  Something very strange about it is that it seems to create .html versions of all my Jade templates in app/assets during the build process, and leaves them there.  Doesn't seem very brunch-like.  Is this just a crappy Brunch plugin?

Any help would be much appreciated!

Thanks,

Tim

**Comment by paulmillr** [comment]
could you paste your brunch-config?

**Comment by Velok** [comment]
I have the exact same problem. I tried it with `jade-brunch` only, with `jade-brunch + static-jade-brunch` and now with `jaded-brunch`. I also deleted the node_modules folder upgraded my npm and reinstalled all the packages.

My App Folder looks like this:

```
.
├── backend
├── libs
├── markup
│   └── index.jade
├── scripts
│   └── app.js
├── static
│   ├── fonts
│   └── images
│       └── bg.png
├── styles
│   └── main.css
└── templates
    └── example.jade

```

Dependencies:

```
"devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "babel-brunch": "^6.0.0",
    "brunch": "^2.2.3",
    "css-brunch": "^2.0.0",
    "jaded-brunch": "^2.2.3",
    "javascript-brunch": "^2.0.0",
    "sass-brunch": "^2.0.0"
  }
```
Configuration:

```
module.exports = config:
  npm:
    enabled: true
  server:
    run: yes
    port: 3000
    hostname: '0.0.0.0'
  conventions:
    assets: [
        /static\//,
        /libs\//
    ]
    ignored: [
      /libs\/_info\.txt/
    ]
    vendor: /#/
  plugins:
    autoReload:
      delay: 0
    jaded:
      staticPatterns: /^app(\/|\\)markup(\/|\\)(.+)\.jade$/
      jade:
        pretty: yes
    babel:
      pattern: /\.(es6|jsx)$/
  files:
    stylesheets: joinTo:
      'app.css': /styles\//
    javascripts: joinTo:
      'app.js': /scripts\//
      'libs.js': /^(?!app\/)/
      'backend/file.js': /backend\/file.*/
    templates: joinTo:
      'templates.js': /templates\//

```
